### ISSUE TITLE
pie chart turns to 5 degrees on focus

### ISSUE THREAD

**Issue by raphaelbogner** [Laiq37/easy_pie_chart#1]
I have a grid with focusable containers, in one of them I use this pie chart package.
I attached two images with 0 degrees start position and a picture that shows the pie chart after I focused the Container with it inside. 
As said in the title, when I focus the Container with the pie chart it turns to about 5 degrees. It does not change anything if the pie chart has a start position of 0 or 90 or anything else, it always turns to around 5 degrees.

![pie_5_degrees](https://github.com/Laiq37/easy_pie_chart/assets/55241467/ce14642f-3952-4eda-a3be-4482db2880ad)
![pie_0_degrees](https://github.com/Laiq37/easy_pie_chart/assets/55241467/15b5282a-7a24-49da-9ce2-b79d1d24adec)

**Comment by Laiq37** [comment]
Hi,
Could you please share the relevant code files to assist in resolving this issue more effectively?

**Comment by faaqi** [comment]
@Laiq37 @raphaelbogner 

I found this bug as well and in my case, I've the Pie chart inside a sheet. When I drag sheet, the pie chart goes to 7 degree angle.

When I assigned the startAngle = 7 , then pie chart remains stable on closing or playing with sheet. Otherwise, for all other angles, when I close the sheet, the pie chart goes to 7 degree angle always.

I'm using the Pie chart inside this sheet : [sliding_panel](https://pub.dev/packages/sliding_up_panel)


https://github.com/Laiq37/easy_pie_chart/assets/61233208/d1c77d7c-65ee-4890-ad52-a5287d905da8

**Comment by faaqi** [comment]
The value of startAngle changes on focus, the value of Pi is constant but Idk why the startAngle value changes on sliding sheet :

    startAngle *= (pi / 180);

When start angle is defined as "-120" from top level. This was calculation "2.0943951023931953"

On sliding the new calculations is as follows :

"0.07310818074881006"
"0.11161023724202036"

**Comment by faaqi** [comment]
Resolved this issue by using another variable for start angle and retaining the initial start angle of pie chart.

Use the new variable at all other places in this clss.

@Laiq37 @raphaelbogner 

![image](https://github.com/Laiq37/easy_pie_chart/assets/61233208/69ac3e59-5512-4e0a-896f-1ea632b7f556)

**Comment by Laiq37** [comment]
Thank you for sharing your solution! I'm glad to hear that it resolved the issue for you. I'll work on fixing this globally. Could you provide more details on how you're using the widget with the sliding_panel package? This information will be valuable in reproducing and addressing the problem effectively. Your feedback is much appreciated!

**Comment by byjoker8625** [comment]
Anything new with this? Im still experiencing the same bug. I would really appreciate if this could get fixed in the lib.

**Comment by vasilich6107** [comment]
@Laiq37
