### ISSUE TITLE
Background colour for the pie chart

### ISSUE THREAD

**Issue by ShiyanaSam** [Laiq37/easy_pie_chart#5]

**Comment by ShiyanaSam** [comment]
Also is it possible to highlight only the tapped pie

**Comment by Laiq37** [comment]
> Also is it possible to highlight only the tapped pie 

Currently, direct highlighting of a specific pie slice on tap isn't supported. However, you can manually change the color of the pie slice upon tap. The PieChart provides a callback that gives the index of the tapped pie. By updating the corresponding PieData in your pie list and refreshing the widget state, you can achieve this effect.

Adding a dedicated highlighting feature is something we can consider for a future update

**Comment by Laiq37** [comment]
did your first issue has been resolved?

**Comment by ShiyanaSam** [comment]
> did your first issue has been resolved?

Yes, thankyou.
Both issues are cleared.

**Comment by Laiq37** [comment]
That's great to hear! I'm glad both issues have been resolved. If you have any more questions or run into any other concerns in the future, feel free to reach out. Happy coding!
